from sqlalchemy import create_engine, Column, Integer, String, Float, DECIMAL, Date, DateTime
from sqlalchemy.ext.declarative import declarative_base

# Declarative base para definir las clases ORM
Base = declarative_base()

class ProductoOrigen(Base):
    __tablename__ = 'productos'

    keycodigo = Column(Integer, primary_key=True, autoincrement=True)
    codprod = Column(Integer, default=0)
    alterno = Column(String(10), default='')
    nombre = Column(String(80), default=None)
    creacion = Column(Date, default=None)
    tipoproducto = Column(String(15), default='Medicinas')
    unidad = Column(String(20), default='')
    empaque = Column(Integer, default=0)
    modelo = Column(String(20), default=' ')
    codlin = Column(Integer, default=0)
    lineas = Column(String(40), default=' ')
    codmarca = Column(Integer, default=0)
    marca = Column(String(40), default=' ')
    codfab = Column(Integer, default=0)
    fabricado = Column(String(40), default=' ')
    codclase = Column(Integer, default=0)
    clase = Column(String(40), default=' ')
    codpactivo = Column(Integer, default=0)
    activagen = Column(Integer, default=0)
    pactivo = Column(String(110), default=' ')
    tipoarti = Column(String(40), default='MEDICINA')
    stock = Column(DECIMAL(10, 3), default=0.000)
    costo = Column(DECIMAL(18, 2), default=0.00)
    costoprom = Column(DECIMAL(18, 2), default=0.00)
    precio = Column(DECIMAL(18, 2), default=0.00)
    tipoIva = Column(String(10), default='EXENTO')
    ubicacion = Column(String(40), default=' ')
    CODBARRA01 = Column(String(20), default='')
    CODBARRA02 = Column(String(20), default='')
    CODBARRA03 = Column(String(20), default='')
    tienelote = Column(Integer, default=1)
    fisico = Column(Integer, default=0)
    minimo = Column(DECIMAL(10, 0), default=0)
    maximo = Column(DECIMAL(10, 0), default=0)
    codalt03 = Column(String(10), default='    ')
    codalt04 = Column(String(10), default='   ')
    encarte = Column(DECIMAL(11, 2), default=0.00)
    inicio = Column(Date, default='1999-01-01')
    final = Column(Date, default='1999-01-01')
    desc_oferta = Column(DECIMAL(18, 2), default=0.00)
    frecuencia = Column(DECIMAL(18, 6), default=0.000000)
    comi_inicio = Column(Date, default=None)
    comi_final = Column(Date, default=None)
    comision = Column(DECIMAL(18, 2), default=0.00)
    activar_comi = Column(Integer, default=0)
    posologia = Column(String(250), default=' ')
    desactivar = Column(Integer, default=0)
    utilreal = Column(DECIMAL(10, 2), default=0.00)
    procodigo = Column(Integer, default=0)
    referen01 = Column(DECIMAL(18, 2), default=0.00)
    referen02 = Column(DECIMAL(18, 2), default=0.00)
    referen03 = Column(DECIMAL(18, 2), default=0.00)
    cerrado = Column(Integer, default=0)
    porcentaje = Column(DECIMAL(12, 2), default=0.00)
    Frec_inicial = Column(DECIMAL(18, 6), default=None)
    noredondear = Column(Integer, default=0)
    tempoiva = Column(DECIMAL(18, 2), default=0.00)
    costop = Column(DECIMAL(18, 2), default=None)
    listo = Column(Integer, default=0)
    tienda = Column(Integer, default=0)
    saldo = Column(DECIMAL(10, 0), default=0)
    fechac = Column(Date, default='1999-01-01')
    costo_s = Column(DECIMAL(18, 2), default=0.00)
    costo_01 = Column(DECIMAL(18, 2), default=0.00)
    costo_02 = Column(DECIMAL(18, 2), default=0.00)
    costo_03 = Column(DECIMAL(18, 2), default=0.00)
    precio_s = Column(DECIMAL(18, 2), default=0.00)
    precio_01 = Column(DECIMAL(18, 2), default=0.00)
    precio_02 = Column(DECIMAL(18, 2), default=0.00)
    precio_03 = Column(DECIMAL(18, 2), default=0.00)
    printhablador = Column(Integer, default=0)
    material = Column(String(30), default=' ')
    cantidad = Column(DECIMAL(10, 2), default=0.00)
    simbolo = Column(String(10), default=' ')
    mpps = Column(String(20), default=' ')
    sencamer = Column(String(20), default=' ')
    costoc = Column(DECIMAL(12, 2), default=0.00)
    codubicacion = Column(Integer, default=0)
    promo = Column(Integer, default=0)
    valorpromo = Column(DECIMAL(12, 2), default=0.00)
    alm2 = Column(DECIMAL(10, 3), default=0.000)
    alm3 = Column(DECIMAL(10, 3), default=0.000)
    alm4 = Column(DECIMAL(10, 3), default=0.000)
    alm5 = Column(DECIMAL(10, 3), default=0.000)
    alm6 = Column(DECIMAL(10, 3), default=0.000)
    codposologia = Column(Integer, default=0)
    ultventa = Column(Date, default='2001-01-01')
    avance = Column(Integer, default=0)  # bandera para indicar que es avance
    manejapeso = Column(Integer, default=0)  # activa lectura de bascula
    sinexist = Column(Integer, default=0)
    segunsepaga = Column(Integer, default=0)
    vcto = Column(Date, default='1999-01-01')
    ingresaprec = Column(Integer, default=0)
    ucambio_precio = Column(Date, default='2000-01-01')
    codpresentacion = Column(Integer, default=0)
    presentacion = Column(String(80), default=' ')
    codpresentacion2 = Column(Integer, default=0)
    presentacion2 = Column(String(80), default=' ')
    codpresentacion3 = Column(Integer, default=0)
    presentacion3 = Column(String(80), default=' ')
    consignacion = Column(Integer, default=0)
    impulsar = Column(Integer, default=0)

    def __repr__(self):
        return f"<ProductoOrigen(codprod={self.codprod}, nombre={self.nombre}, precio={self.precio}, stock={self.stock})>"
